name: flutterapplication
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.15.3  # Add version number
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6  # Add this for Firestore
  bloc: ^8.1.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_app_check: ^0.2.1+6
  
  user_repository:
    path: packages/user_repository

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true